# Introduction 

## About the course 

This is the 3rd run of this rather newly developed course. The purpose of this course is to provide students with learning opportunities to understand fundamental epidemiological concepts through the application of methods using population and public health datasets. The purpose is also to introduce students to emerging epidemiological methodologies that are frequently being applied to population and public health-related research questions in prestigious epidemiology journal publications.

## Course Learning Objectives 

Design an appropriate study for a population/public health research question that will help reduce bias;
  - Create an analytic dataset from a complex population/public health survey to answer an epidemiological research question, including statistical programming/coding and data management/documentation skills;
  - Recognize the scenarios where various data analysis methods are appropriate to answer a research question;
  - Apply an appropriate data analysis method to answer a population/public health research question;
  - Interpret estimates and conclusions from data analysis methods;
  - Describe the assumptions and limitations of data analysis methods;
  - Communicate an epidemiological study (design, analytic method, findings, and discussion; including issues related to limitations, biases) in a format suitable for submission to an academic health journal; and
  - Present an epidemiological study and analytic method in a format suitable for an academic health conference.
